### ISSUE TITLE
Rename Application "environment" to something like "SAPI"

### ISSUE THREAD

**Issue by dschissler** [dschissler/schmalcon#2]
Currently the Application class uses the term "environment" to refer to either web or cli.  This conflicts with typical use of environment as being development, production, testing, etc.  So new language needs to be used for this current use of the term environment.

**Comment by dschissler** [comment]
However SAPI doesn't quite fit because we don't care about how the web environment is being reached, for example by mod_php or FPM.  So time to hit the thesaurus.

**Comment by Ultimater** [comment]
Maybe formulation, infrastructure, or network? Hmm... what do web and cli have to do with the environment? It's how the app is launched, perhaps we're looking for something more like: dispatcher, or starter? establishment? Activator? hmm...

**Comment by dschissler** [comment]
"environment` was changed to `runmode`.
